version: '3.8'

services:
  telesubmit:
    build: 
      context: .
      network: host  # 使用宿主机网络进行构建
      # 代理参数（可选，通过 deploy.sh 的 --proxy 参数传入）
      # args:
      #   - HTTP_PROXY=${HTTP_PROXY}
      #   - HTTPS_PROXY=${HTTPS_PROXY}
    container_name: telesubmit-v2
    restart: unless-stopped
    
    # DNS 配置 - 使用真实 DNS 服务器
    dns:
      - 8.8.8.8
      - 114.114.114.114
      - 1.1.1.1
    
    # 挂载配置文件和数据目录
    volumes:
      - ./config.ini:/app/config.ini:ro      # 只读挂载配置文件
      - ./data:/app/data                      # 持久化数据库和搜索索引
      - ./logs:/app/logs                      # 持久化日志文件
      # 开发模式：挂载代码目录以便实时更新（生产环境建议删除以下挂载）
      - ./handlers:/app/handlers
      - ./utils:/app/utils
      - ./config:/app/config
      - ./ui:/app/ui
      - ./main.py:/app/main.py
    
    # 环境变量（可选，会覆盖config.ini中的配置）
    environment:
      - TZ=Asia/Shanghai
      # Telegram Bot 配置
      # - TOKEN=your_bot_token_here
      # - CHANNEL_ID=@your_channel_name
      # - OWNER_ID=your_user_id
      
      # 功能开关
      # - SHOW_SUBMITTER=true
      # - NOTIFY_OWNER=true
      # - BOT_MODE=MIXED
      
      # 搜索引擎配置
      # - SEARCH_INDEX_DIR=data/search_index
    
    # 资源限制
    # v2 版本因搜索功能需要更多内存
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 256M
    
    # 日志配置
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    
    # 网络模式
    network_mode: bridge
    
    # 健康检查
    healthcheck:
      test: ["CMD", "python", "-c", "import os, psutil; exit(0 if any('main.py' in ' '.join(p.cmdline()) for p in psutil.process_iter(['cmdline'])) else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

